from functions.run_python_file import run_python_file
print("Result for current directory:")
print(run_python_file("calculator", "main.py"))
print("")
print("Result for current directory:")
print(run_python_file("calculator", "main.py", ["3 + 5"]))
print("")
print("Result for current directory:")
print(run_python_file("calculator", "tests.py"))
print("")
print("Result for current directory:")
print(run_python_file("calculator", "../main.py"))
print("")
print("Result for current directory:")
print(run_python_file("calculator", "nonexistent.py"))
print("")
print("Result for current directory:")
print(run_python_file("calculator", "lorem.txt"))
print("")
